---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
  labels:
    app: consul
spec:
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:1.3.0
        ports:
        - name: ui
          containerPort: 8500
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - agent
        - -ui
        - -bootstrap-expect=3
        - -server
        - -client=0.0.0.0
        - -retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local
        - -retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local
        - -retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local
        - -data-dir=/var/lib/consul
        volumeMounts:
        - name: consul
          mountPath: /var/lib/consul
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - consul leave
  volumeClaimTemplates:
  - metadata:
      name: consul
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  clusterIP: None
  ports:
  - name: http
    port: 8500
    targetPort: 8500
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul
spec:
  rules:
  - host: consul.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: consul
          servicePort: 8500
